hub_settings:
  id: 0
  port: 5555
  broadcast_id: 4294967295
  virtual_position: [0, 0]
  address: "127.0.0.1"

paths:
  build_dir: "../build"


gnb_settings:
  radius: 1200
  node_settings:
    cell:
      tracking_area_code: 100
    radio:
      radio_frame_duration: 10
      tx_power_db: 43.0

ue_settings:
  node_settings:
    cell:
      tracking_area_code: 100
    radio:
      radio_frame_duration: 10
      tx_power_db: 5.0

simulation:
  deploy_local_node: true
  gnb_id_start: 1
  ue_id_start: 501
  gnb_count: 3
  ue_count: 15

positions:
  gnb_positions_list:
    - id: 101
      pos: [ -1800, -1000 ]
    - id: 102
      pos: [ 1800, -1400 ]
    - id: 103
      pos: [ 0, 1300 ]

  ue_positions_list:
    - id: 501
      pos: [ 2300, -1300 ]
    - id: 502
      pos: [ -2400, -2400 ]
    - id: 503
      pos: [ -2000, -400 ]
    - id: 504
      pos: [ -180, 1610 ]
    - id: 505
      pos: [ -1000, 1610 ]
    - id: 506
      pos: [ -2700, 840 ]
    - id: 507
      pos: [ 1544, -2980 ]
    - id: 508
      pos: [ 1290, -530 ]
    - id: 509
      pos: [ -360, 2060 ]
    - id: 510
      pos: [ 120, 1780 ]
    - id: 511
      pos: [ -250, -1170 ]
    - id: 512
      pos: [ -2350, -1140 ]
    - id: 513
      pos: [ 1170, -1950 ]
    - id: 514
      pos: [ 1600, -3000 ]
    - id: 515
      pos: [ 1500, -2540 ]

