name: 5G-RAN-Simulator CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang-format-15 \
            libyaml-cpp-dev \
            cmake \
            build-essential \
            qt6-base-dev \
            google-mock \
            libgtest-dev

      - name: Check Clang Version
        run: clang --version

      - name: Check Code Formatting
        run: |
          find . -regex '.*\.\(cpp\|hpp\|h\)' -not -path "*/build*/*" | xargs --no-run-if-empty clang-format-15 --dry-run --Werror


      - name: Build and Install GTest/GMock
        run: |
          cd /usr/src/googletest
          sudo mkdir -p build
          cd build
          sudo cmake ..
          sudo make
          sudo make install

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: c-cpp
          queries: security-and-quality

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON

      - name: Build Project
        run: cmake --build build --parallel $(nproc)

      - name: Run All 5G-RAN-Simulator Tests
        run: |
          cd build
          ctest --output-on-failure
